[COMMON]
PROJECT_NAME = data-pipeline
CHANNEL_NAME = test

[IMDG]
SERVER_IP = 127.0.0.1
; SERVER_IP = redis
SERVER_PORT = 6379
POOL_SIZE = 10
SCHEMA_NAME = COM

[REST]
BIND_IP = 0.0.0.0
BIND_PORT = 9999

[STREAM]
STREAM_NAME = downloader_tasks
GROUP_NAME = downloader_group

[STORAGE]
ROOT = /home/shinminbeom/infra_glue/personal/data-pipeline/data
PREFIX = raw
